home:
    path: /
    controller: App\Controller\HomeController::index
penguin:
    path: /pingu
    controller: App\Controller\HomeController::penguin

astro:
    path: /astro
    controller: App\Controller\AstroController::list

p5:
    path: /p5
    controller: App\Controller\ProcessingController::index